import TrustCenterPage from "@/components/trust-center-page";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "KVKK Aydınlatma Metni | Dromocob", description: "6698 sayılı KVKK kapsamında Dromocob kişisel veri işleme amaçları, yöntemleri, hukuki sebepleri, aktarım çerçevesi ve ilgili kişi hakları.", path: "/kvkk-aydinlatma", keywords: ["KVKK aydınlatma metni", "Dromocob KVKK", "kişisel veri başvurusu"] });

const sections = [
  { id: "sorumlu", title: "Veri sorumlusu", summary: "Dromocob, dromocob.tr ve doğrudan sunduğu hizmetlerde elde edilen kişisel veriler bakımından ilgili faaliyetin niteliğine göre veri sorumlusu olarak hareket eder.", paragraphs: ["Aydınlatma ve ilgili kişi başvuruları için info@dromocob.tr adresinden iletişim kurulabilir. Başvurunun güvenli sonuçlandırılması amacıyla kimlik veya talep sahipliğini doğrulayıcı ek bilgi istenebilir."] },
  { id: "kategoriler", title: "İşlenen veri kategorileri", summary: "Hizmet ve iletişim türüne göre sınırlı veri kategorileri işlenebilir.", items: ["Kimlik: ad ve soyad", "İletişim: e-posta, telefon, şehir ve tercih edilen kanal", "Müşteri işlem: teklif seçimleri, talep, proje ve destek mesajları", "İşlem güvenliği: IP, cihaz, tarayıcı, oturum ve teknik günlük bilgileri", "Pazarlama: bülten tercihi ile izin verilen analitik/reklam etkileşimleri"] },
  { id: "amaclar", title: "İşleme amaçları", summary: "Kişisel veriler yalnızca açıkça belirlenen iş ve güvenlik amaçlarıyla işlenir.", items: ["İletişim, teklif, sözleşme ve proje süreçlerini yürütmek", "Canlı destek ve satış sonrası hizmet sağlamak", "Dijital ürün, lisans ve hesap güvenliğini korumak", "Muhasebe, hukuk ve resmî yükümlülükleri yerine getirmek", "Tercih verilmişse analitik ve reklam performansını ölçmek"] },
  { id: "yontem", title: "Toplama yöntemi ve hukuki sebep", summary: "Veriler elektronik formlar, canlı destek, e-posta, telefon, sözleşme süreçleri ve teknik günlükler üzerinden otomatik veya kısmen otomatik yöntemlerle elde edilebilir.", paragraphs: ["Faaliyetin niteliğine göre Kanun’da öngörülme, sözleşmenin kurulması veya ifası, hukuki yükümlülüğün yerine getirilmesi, bir hakkın tesisi/kullanılması/korunması, temel haklara zarar vermemek kaydıyla meşru menfaat ve gerektiğinde açık rıza işleme şartlarından uygun olanına dayanılır. Açık rızaya dayanan süreçlerde rıza, aydınlatmadan ayrı olarak alınır ve geri çekilebilir."] },
  { id: "aktarim", title: "Aktarım yapılan taraflar ve amaç", summary: "Kişisel veriler satılmaz; teknik hizmetin sunumu ve hukuki gerekliliklerle sınırlı aktarım yapılabilir.", items: ["Barındırma, veritabanı, e-posta ve bildirim hizmeti sağlayıcılarına teknik işletim amacıyla", "Analitik ve reklam platformlarına yalnızca ilgili tercih ve ölçüm kapsamıyla", "Mali müşavir, hukuk danışmanı veya iş ortağına hizmetin gerektirdiği ölçüde", "Yetkili kamu kurumlarına hukuken geçerli talep veya yükümlülük halinde"] },
  { id: "haklar", title: "KVKK kapsamındaki haklar", summary: "Kanun’un 11. maddesi kapsamındaki taleplerinizi veri sorumlusuna iletebilirsiniz.", items: ["Kişisel veri işlenip işlenmediğini öğrenme ve bilgi talep etme", "İşleme amacını ve amaca uygun kullanılıp kullanılmadığını öğrenme", "Aktarılan üçüncü kişileri öğrenme", "Eksik veya yanlış işlenen verinin düzeltilmesini isteme", "Şartları oluştuğunda silme/yok etme ve aktarılan taraflara bildirilmesini isteme", "Otomatik analiz sonucu aleyhe sonuca itiraz etme ve kanuna aykırılık nedeniyle zararın giderilmesini talep etme"] },
  { id: "basvuru", title: "Başvuru yöntemi", summary: "Talep konusu açıkça belirtilerek info@dromocob.tr adresine başvurulabilir.", paragraphs: ["Başvuruda ad-soyad, ulaşılabilir iletişim bilgisi, talebin konusu ve varsa destekleyici belgelerin bulunması önerilir. Dromocob, başvuruyu mevzuatta öngörülen yöntem ve süreler içinde değerlendirir; kimlik doğrulaması ve güvenli yanıt için ek bilgi talep edebilir."] },
];

export default function KvkkPage() { return <TrustCenterPage eyebrow="TRUST CENTER / KVKK" title="KVKK" accent="Aydınlatma Metni" description="Kişisel verilerinizin kim tarafından, hangi amaç ve hukuki sebeple işlendiğini; kimlere aktarılabileceğini ve haklarınızı açıklıyoruz." documentCode="DC-KVKK / V2.0" updatedAt="13 Ağustos 2026" sections={sections} note="Aydınlatma yükümlülüğü açık rızadan bağımsızdır; açık rıza gereken süreçlerde ayrıca ve aktif tercihinizle alınır." related={[{ title: "Gizlilik Politikası", href: "/gizlilik-politikasi" }, { title: "Uygulama Gizliliği", href: "/gizlilik" }, { title: "Destek Merkezi", href: "/destek" }]}/>; }
