export const DEFAULT_GOOGLE_ADS_ID = "AW-18343146345";
export const DEFAULT_GOOGLE_ADS_CONVERSION_LABEL = "bDvtC0u02tccE0nm2KpE";
export const DEFAULT_GOOGLE_ADS_QUICK_QUOTE_LABEL = DEFAULT_GOOGLE_ADS_CONVERSION_LABEL;
export const DEFAULT_GOOGLE_ADS_SELL_REQUEST_LABEL = DEFAULT_GOOGLE_ADS_CONVERSION_LABEL;
