"use client";

import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, CircleDollarSign, Download, Loader2, MousePointerClick, RefreshCw, Send, Target } from "lucide-react";
import { auth } from "@/lib/firebase";

type Conversion = Record<string, unknown>;
type AdsData = { configuration: { googleAdsId: string; conversionLabel: string; consentMode: boolean }; summary: { conversions: number; quotes: number; attributed: number; totalValue: number; attributionRate: number }; campaigns: Array<{ name: string; conversions: number; value: number }>; conversions: Conversion[] };

function money(value: unknown) { return `${Number(value || 0).toLocaleString("tr-TR")} TL`; }
function date(value: unknown) { const parsed = new Date(String(value)); return Number.isNaN(parsed.valueOf()) ? "—" : parsed.toLocaleString("tr-TR"); }

export default function AdsControlCenter() {
  const [data, setData] = useState<AdsData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const user = auth.currentUser; if (!user) throw new Error("Admin oturumu bulunamadı."); const response = await fetch("/api/admin/ads", { headers: { authorization: `Bearer ${await user.getIdToken()}` }, cache: "no-store" }); if (!response.ok) throw new Error(await response.text()); setData(await response.json()); setError(""); } catch (value) { setError(value instanceof Error ? value.message : "Ads verileri alınamadı."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function downloadCsv() { const user = auth.currentUser; if (!user) return; const response = await fetch("/api/admin/ads?format=csv", { headers: { authorization: `Bearer ${await user.getIdToken()}` } }); if (!response.ok) { setError(await response.text()); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `dromocob-google-ads-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  if (loading && !data) return <div className="analytics-loading"><Loader2 className="spin"/>Ads dönüşüm merkezi hazırlanıyor</div>;
  return <div className="ads-center">
    <div className="admin-title"><div><p className="admin-kicker">GOOGLE ADS / CONVERSION INTELLIGENCE</p><h1>Ads Dönüşüm Merkezi</h1><p>Reklam tıklamasından teklif değerine kadar dönüşüm zincirini tek ekranda yönet.</p></div><div className="ads-actions"><button className="admin-action" onClick={() => void load()}><RefreshCw size={15}/> Yenile</button><button className="admin-action ads-primary" onClick={() => void downloadCsv()}><Download size={15}/> Google Ads CSV</button></div></div>
    {error && <div className="admin-alert">{error}</div>}
    <section className="ads-health"><div><span className={data?.configuration.googleAdsId ? "ok" : ""}><BadgeCheck/></span><small>GOOGLE TAG</small><strong>{data?.configuration.googleAdsId || "Bağlantı bekliyor"}</strong></div><div><span className={data?.configuration.conversionLabel ? "ok" : ""}><Target/></span><small>CONVERSION LABEL</small><strong>{data?.configuration.conversionLabel || "Etiket eksik"}</strong></div><div><span className={data?.configuration.consentMode ? "ok" : ""}><BadgeCheck/></span><small>CONSENT MODE V2</small><strong>{data?.configuration.consentMode ? "Aktif" : "Kontrol gerekli"}</strong></div></section>
    <section className="ads-metrics"><article><MousePointerClick/><small>TOPLAM DÖNÜŞÜM</small><strong>{data?.summary.conversions || 0}</strong></article><article><Send/><small>TEKLİF TALEBİ</small><strong>{data?.summary.quotes || 0}</strong></article><article><Target/><small>ADS EŞLEŞME</small><strong>%{data?.summary.attributionRate || 0}</strong></article><article><CircleDollarSign/><small>POTANSİYEL DEĞER</small><strong>{money(data?.summary.totalValue)}</strong></article></section>
    <div className="ads-layout"><section className="admin-panel ads-campaigns"><header><div><small>ATTRIBUTION MAP</small><h2>Kampanya performansı</h2></div></header>{data?.campaigns.length ? data.campaigns.map(item => <article key={item.name}><div><strong>{item.name}</strong><small>{item.conversions} dönüşüm</small></div><b>{money(item.value)}</b></article>) : <p className="empty-state">İlk dönüşüm bekleniyor.</p>}</section><section className="admin-panel ads-guide"><small>SAĞLAM KURULUM</small><h2>Aktif ölçüm zinciri</h2><ol><li><b>01</b> Reklam tıklama kimliği 90 gün saklanır.</li><li><b>02</b> Form işlemi tekil sipariş ID ile kaydolur.</li><li><b>03</b> Google etiketi ve GA4 generate_lead tetiklenir.</li><li><b>04</b> Eşleşen kayıtlar CSV ile yeniden yüklenebilir.</li></ol></section></div>
    <section className="admin-panel ads-table"><header><div><small>CONVERSION LEDGER</small><h2>Son dönüşümler</h2></div><span>{data?.conversions.length || 0} kayıt</span></header><div className="ads-table-scroll"><table><thead><tr><th>Tarih</th><th>Dönüşüm</th><th>Müşteri / Hizmet</th><th>Kaynak</th><th>Click ID</th><th>Değer</th></tr></thead><tbody>{data?.conversions.map(item => <tr key={String(item.id)}><td>{date(item.occurredAt)}</td><td><strong>{String(item.conversionName || "Lead")}</strong><small>{String(item.id)}</small></td><td><strong>{String(item.customerName || "—")}</strong><small>{String(item.service || "—")}</small></td><td>{String(item.utmCampaign || item.utmSource || "Organik / Doğrudan")}</td><td><span className={item.gclid || item.gbraid || item.wbraid ? "ads-match yes" : "ads-match"}>{item.gclid || item.gbraid || item.wbraid ? "Eşleşti" : "Yok"}</span></td><td><b>{money(item.value)}</b></td></tr>)}</tbody></table></div></section>
  </div>;
}
