"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Check, Copy, Eye, EyeOff, Loader2, Megaphone, MousePointerClick, Plus, Save, Trash2, X } from "lucide-react";
import { auth } from "@/lib/firebase";
import { DEFAULT_ENTRY_ADS_CONFIG, type EntryAdCampaign, type EntryAdsConfig, type EntryAdDevice, type EntryAdFrequency } from "@/lib/entry-ads";
import type { AdvancedQuoteService } from "@/lib/advanced-quote-config";

type CampaignStats = Record<string, { impressions: number; cta: number; dismiss: number }>;
const services: AdvancedQuoteService[] = ["web-quick","video-quick","drone-quick","growth-quick","apps-quick","project-quick","fethiye-quick","equipment-quick"];
const blankCampaign = (): EntryAdCampaign => ({ ...DEFAULT_ENTRY_ADS_CONFIG.campaigns[0], id:`campaign-${Date.now()}`,name:"Yeni kampanya",active:false,priority:0,routePatterns:["/hizmetler*"],eyebrow:"DROMOCOB / NEW CAMPAIGN",title:"Yeni bir fikir,",accent:"güçlü bir başlangıç.",description:"Kampanya mesajını buradan düzenle.",chips:["Özel kapsam","Hızlı başlangıç","Net plan"],metric:"NEW",metricLabel:"CAMPAIGN",cta:"Kapsamı başlat",nodes:["KEŞİF","PLAN","SONUÇ"] });

export default function EntryAdsControlCenter() {
  const [config, setConfig] = useState<EntryAdsConfig>(DEFAULT_ENTRY_ADS_CONFIG);
  const [stats, setStats] = useState<CampaignStats>({});
  const [selectedId, setSelectedId] = useState(DEFAULT_ENTRY_ADS_CONFIG.campaigns[0].id);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");
  const selectedIndex = config.campaigns.findIndex(item => item.id === selectedId);
  const selected = config.campaigns[selectedIndex] || config.campaigns[0];
  const totals = useMemo(() => Object.values(stats).reduce((sum, item) => ({ impressions: sum.impressions + item.impressions, cta: sum.cta + item.cta, dismiss: sum.dismiss + item.dismiss }), { impressions:0,cta:0,dismiss:0 }), [stats]);

  async function api(init?: RequestInit) { const token = await auth.currentUser?.getIdToken(); const response = await fetch("/api/admin/entry-ads", { ...init, headers:{ "content-type":"application/json", authorization:`Bearer ${token}`, ...init?.headers } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "İşlem tamamlanamadı."); return payload; }
  useEffect(() => { api().then(payload => { setConfig(payload.config); setStats(payload.stats || {}); setSelectedId(payload.config.campaigns[0]?.id || ""); }).catch(error => setNotice(error.message)).finally(() => setLoading(false)); }, []);
  function update(patch: Partial<EntryAdCampaign>) { setConfig(current => ({ ...current, campaigns: current.campaigns.map((item, index) => index === selectedIndex ? { ...item, ...patch } : item) })); }
  function addCampaign() { const next = blankCampaign(); setConfig(current => ({ ...current, campaigns:[...current.campaigns,next] })); setSelectedId(next.id); }
  function duplicate() { if (!selected) return; const next = { ...selected, id:`${selected.id}-copy-${Date.now()}`, name:`${selected.name} — Kopya`, active:false }; setConfig(current => ({ ...current, campaigns:[...current.campaigns,next] })); setSelectedId(next.id); }
  function remove() { if (!selected || config.campaigns.length <= 1) return; const remaining = config.campaigns.filter(item => item.id !== selected.id); setConfig({ ...config, campaigns:remaining }); setSelectedId(remaining[0].id); }
  async function save() { setSaving(true); setNotice(""); try { const payload = await api({ method:"PUT",body:JSON.stringify(config) }); setConfig(payload.config); setNotice("Açılış reklamları yayına alındı."); } catch (error) { setNotice(error instanceof Error ? error.message : "Kaydedilemedi."); } finally { setSaving(false); } }
  if (loading) return <div className="admin-loading"><Loader2 className="spin"/> Reklam sistemi yükleniyor</div>;

  const selectedStats = stats[selected?.id] || { impressions:0,cta:0,dismiss:0 };
  const conversion = selectedStats.impressions ? Math.round(selectedStats.cta / selectedStats.impressions * 1000) / 10 : 0;
  return <div className="entry-ads-admin">
    <section className="entry-ads-metrics"><article><Eye/><span><small>GÖSTERİM</small><strong>{totals.impressions.toLocaleString("tr-TR")}</strong></span></article><article><MousePointerClick/><span><small>CTA TIKLAMA</small><strong>{totals.cta.toLocaleString("tr-TR")}</strong></span></article><article><BarChart3/><span><small>GENEL ORAN</small><strong>%{totals.impressions ? Math.round(totals.cta / totals.impressions * 1000) / 10 : 0}</strong></span></article></section>
    <section className="admin-panel entry-ads-global"><header><div><small>GLOBAL DELIVERY CONTROL</small><h2>Yayın kuralları</h2></div><label className="entry-ad-switch"><input type="checkbox" checked={config.active} onChange={event => setConfig({ ...config, active:event.target.checked })}/><span/>{config.active ? "Sistem açık" : "Sistem kapalı"}</label></header><div><label>Gösterim gecikmesi<input type="number" min="0" max="30000" step="100" value={config.delayMs} onChange={event => setConfig({ ...config, delayMs:Number(event.target.value) })}/><small>milisaniye</small></label><label>Sıklık<select value={config.frequency} onChange={event => setConfig({ ...config, frequency:event.target.value as EntryAdFrequency })}><option value="once_session">Oturumda bir kez</option><option value="once_day">Günde bir kez</option><option value="always">Her uygun sayfada</option></select></label><label>Oturum üst sınırı<input type="number" min="1" max="20" value={config.maxShowsPerSession} onChange={event => setConfig({ ...config, maxShowsPerSession:Number(event.target.value) })}/></label><label className="wide">Hariç tutulan yollar<textarea rows={3} value={config.excludedPaths.join("\n")} onChange={event => setConfig({ ...config, excludedPaths:event.target.value.split("\n").map(item => item.trim()).filter(Boolean) })}/><small>Her satıra bir yol; * joker karakterdir.</small></label></div></section>
    <div className="entry-ads-workspace">
      <aside className="admin-panel entry-ads-list"><header><div><small>{config.campaigns.length} CAMPAIGN</small><h2>Kampanyalar</h2></div><button type="button" onClick={addCampaign}><Plus/></button></header><nav>{[...config.campaigns].sort((a,b) => b.priority-a.priority).map(item => <button type="button" key={item.id} className={item.id === selectedId ? "active" : ""} onClick={() => setSelectedId(item.id)}><span style={{ background:`linear-gradient(135deg,${item.color},${item.color2})` }}>{item.active ? <Megaphone/> : <EyeOff/>}</span><div><strong>{item.name}</strong><small>{item.routePatterns.join(" · ")}</small></div><i className={item.active ? "is-live" : ""}/></button>)}</nav></aside>
      {selected && <section className="admin-panel entry-ad-editor"><header><div><small>CAMPAIGN / {selected.id}</small><h2>{selected.name}</h2></div><div><button type="button" onClick={duplicate}><Copy/> Kopyala</button><button type="button" className="danger" onClick={remove} disabled={config.campaigns.length <= 1}><Trash2/></button></div></header>
        <div className="entry-ad-editor-stats"><span><small>GÖSTERİM</small><strong>{selectedStats.impressions}</strong></span><span><small>TIKLAMA</small><strong>{selectedStats.cta}</strong></span><span><small>DÖNÜŞÜM</small><strong>%{conversion}</strong></span><span><small>KAPATMA</small><strong>{selectedStats.dismiss}</strong></span></div>
        <div className="entry-ad-form"><label>Kampanya adı<input value={selected.name} onChange={event => update({ name:event.target.value })}/></label><label>Kampanya kimliği<input value={selected.id} onChange={event => { const id=event.target.value.replace(/[^a-z0-9-]/gi,"-").toLowerCase(); update({ id }); setSelectedId(id); }}/></label><label className="toggle-row"><input type="checkbox" checked={selected.active} onChange={event => update({ active:event.target.checked })}/><span>{selected.active ? <Check/> : <X/>}</span>Yayında</label><label>Öncelik<input type="number" value={selected.priority} onChange={event => update({ priority:Number(event.target.value) })}/></label><label>Cihaz<select value={selected.device} onChange={event => update({ device:event.target.value as EntryAdDevice })}><option value="all">Tüm cihazlar</option><option value="desktop">Sadece masaüstü</option><option value="mobile">Sadece mobil</option></select></label><label>Teklif motoru<select value={selected.quoteService} onChange={event => update({ quoteService:event.target.value as AdvancedQuoteService })}>{services.map(item => <option key={item}>{item}</option>)}</select></label><label>Başlangıç<input type="datetime-local" value={selected.startAt} onChange={event => update({ startAt:event.target.value })}/></label><label>Bitiş<input type="datetime-local" value={selected.endAt} onChange={event => update({ endAt:event.target.value })}/></label><label className="wide">Hedef yollar<textarea rows={2} value={selected.routePatterns.join("\n")} onChange={event => update({ routePatterns:event.target.value.split("\n").map(item => item.trim()).filter(Boolean) })}/></label>
          <div className="entry-ad-section-title wide"><span>01</span><div><strong>Mesaj ve aksiyon</strong><small>Ziyaretçinin ilk gördüğü reklam içeriği.</small></div></div><label className="wide">Üst etiket<input value={selected.eyebrow} onChange={event => update({ eyebrow:event.target.value })}/></label><label>Başlık<input value={selected.title} onChange={event => update({ title:event.target.value })}/></label><label>Vurgulu başlık<input value={selected.accent} onChange={event => update({ accent:event.target.value })}/></label><label className="wide">Açıklama<textarea rows={3} value={selected.description} onChange={event => update({ description:event.target.value })}/></label><label>CTA metni<input value={selected.cta} onChange={event => update({ cta:event.target.value })}/></label><label>Metrik<input value={selected.metric} onChange={event => update({ metric:event.target.value })}/></label><label>Metrik etiketi<input value={selected.metricLabel} onChange={event => update({ metricLabel:event.target.value })}/></label>
          <div className="entry-ad-section-title wide"><span>02</span><div><strong>Görsel sinyaller</strong><small>Renk, fayda etiketleri ve animasyon düğümleri.</small></div></div><label>Birinci renk<input type="color" value={selected.color} onChange={event => update({ color:event.target.value })}/></label><label>İkinci renk<input type="color" value={selected.color2} onChange={event => update({ color2:event.target.value })}/></label>{selected.chips.map((chip,index) => <label key={`chip-${index}`}>Fayda {index+1}<input value={chip} onChange={event => { const chips=[...selected.chips] as [string,string,string]; chips[index]=event.target.value; update({ chips }); }}/></label>)}{selected.nodes.map((node,index) => <label key={`node-${index}`}>Düğüm {index+1}<input value={node} onChange={event => { const nodes=[...selected.nodes] as [string,string,string]; nodes[index]=event.target.value; update({ nodes }); }}/></label>)}</div>
        <div className="entry-ad-preview" style={{ "--preview-a":selected.color,"--preview-b":selected.color2 } as React.CSSProperties}><small>{selected.eyebrow}</small><h3>{selected.title}<em>{selected.accent}</em></h3><p>{selected.description}</p><button type="button">{selected.cta}</button><i/></div>
      </section>}
    </div>
    <footer className="entry-ads-save">{notice && <span>{notice}</span>}<button type="button" onClick={save} disabled={saving}>{saving ? <Loader2 className="spin"/> : <Save/>}{saving ? "Yayınlanıyor" : "Kaydet ve yayınla"}</button></footer>
  </div>;
}
