"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { auth } from "@/lib/firebase";
import { Activity, AppWindow, Ban, CheckCircle2, Copy, KeyRound, Laptop, Plus, RefreshCw, Search, ShieldCheck, Users } from "lucide-react";

type Row = Record<string, unknown> & { id: string };
const products = [
  ["dromocob-all-apps", "Dromocob Apps — Tümü"], ["pixel-resizer-pro", "Pixel Resizer PRO"], ["ai-upscaler", "AI Upscaler"],
  ["background-remover", "Background Remover"], ["watermark-studio", "Watermark Studio"], ["image-compressor", "Image Compressor"], ["video-converter", "Video Converter"],
];

async function token() { const value = await auth.currentUser?.getIdToken(); if (!value) throw new Error("Admin oturumu bulunamadı."); return value; }

export default function LicenseControlCenter() {
  const [licenses, setLicenses] = useState<Row[]>([]), [activations, setActivations] = useState<Row[]>([]), [events, setEvents] = useState<Row[]>([]);
  const [busy, setBusy] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [showCreate, setShowCreate] = useState(false), [createdKey, setCreatedKey] = useState("");
  const [trialDays, setTrialDays] = useState("7"), [savingTrial, setSavingTrial] = useState(false);
  const [form, setForm] = useState({ ownerEmail: "", customerName: "", plan: "pro", product: "dromocob-all-apps", maxDevices: "2", expiresAt: "", offlineGraceDays: "7", notes: "" });
  const load = useCallback(async () => { try { const idToken = await token(); setBusy(true); setError(""); const response = await fetch("/api/admin/licenses", { headers: { Authorization: `Bearer ${idToken}` }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Lisans verileri alınamadı."); setLicenses(data.licenses || []); setActivations(data.activations || []); setEvents(data.events || []); setTrialDays(String(data.settings?.trialDays || 7)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Lisans verileri alınamadı."); } finally { setBusy(false); } }, []);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  const visible = useMemo(() => licenses.filter(item => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())), [licenses, query]);
  async function createLicense(event: React.FormEvent) { event.preventDefault(); setError(""); try { const response = await fetch("/api/admin/licenses", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ ...form, products: [form.product], maxDevices: Number(form.maxDevices), offlineGraceDays: Number(form.offlineGraceDays), expiresAt: form.expiresAt || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Lisans oluşturulamadı."); setCreatedKey(data.licenseKey); setShowCreate(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Lisans oluşturulamadı."); } }
  async function updateStatus(id: string, status: string) { if (status === "revoked" && !window.confirm("Lisans iptal edilecek ve tüm cihaz oturumları kapatılacak. Devam edilsin mi?")) return; const response = await fetch(`/api/admin/licenses/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ status }) }); if (!response.ok) setError("Lisans durumu güncellenemedi."); else await load(); }
  async function saveTrialDays() { setSavingTrial(true); setError(""); try { const response = await fetch("/api/admin/licenses", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ trialDays: Number(trialDays) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Deneme süresi güncellenemedi."); setTrialDays(String(data.settings.trialDays)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Deneme süresi güncellenemedi."); } finally { setSavingTrial(false); } }
  return <div className="license-os">
    <div className="admin-title license-title"><div><p>DROMOCOB / LICENSE CLOUD</p><h1>Lisans Kontrol Merkezi</h1><p>Tek hesap, tek lisans altyapısı, bütün Dromocob uygulamaları.</p></div><button className="admin-action" onClick={() => setShowCreate(true)}><Plus size={16}/> Yeni lisans</button></div>
    <div className="license-metrics"><Metric icon={KeyRound} label="Toplam lisans" value={licenses.length}/><Metric icon={CheckCircle2} label="Aktif lisans" value={licenses.filter(x => x.status === "active").length}/><Metric icon={Laptop} label="Aktif cihaz" value={activations.filter(x => x.active === true).length}/><Metric icon={Users} label="Müşteri" value={new Set(licenses.map(x => String(x.ownerEmail || ""))).size}/></div>
    <section className="admin-panel" style={{display:"flex", alignItems:"center", justifyContent:"space-between", gap:18, padding:20, marginBottom:18}}><div><strong>Ücretsiz kullanım süresi</strong><p style={{margin:"5px 0 0", opacity:.68}}>Yeni kurulumlar lisans istemeden bu süre boyunca tüm özellikleri kullanır.</p></div><div style={{display:"flex", alignItems:"center", gap:10}}><input aria-label="Deneme süresi" type="number" min="1" max="30" value={trialDays} onChange={e => setTrialDays(e.target.value)} style={{width:76}}/><span>gün</span><button className="admin-action" onClick={() => void saveTrialDays()} disabled={savingTrial}>{savingTrial ? "Kaydediliyor…" : "Süreyi kaydet"}</button></div></section>
    {error && <div className="admin-alert">{error}</div>}
    {createdKey && <div className="license-key-reveal"><ShieldCheck/><div><small>YALNIZCA ŞİMDİ GÖSTERİLİR</small><strong>{createdKey}</strong></div><button onClick={() => navigator.clipboard.writeText(createdKey)}><Copy size={16}/> Kopyala</button><button onClick={() => setCreatedKey("")}>Kapat</button></div>}
    <div className="license-toolbar"><label><Search size={15}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Lisans, müşteri veya e-posta ara"/></label><button onClick={() => void load()} disabled={busy}><RefreshCw size={15} className={busy ? "spin" : ""}/> Yenile</button></div>
    <div className="license-layout"><section className="admin-panel license-list"><PanelHead icon={KeyRound} title="Lisanslar" subtitle="Plan, cihaz ve ürün kapsamı"/>{busy ? <div className="empty-state">Lisans ağı senkronize ediliyor…</div> : visible.length === 0 ? <div className="empty-state">Lisans bulunamadı.</div> : visible.map(item => <article key={item.id}><div className="license-avatar"><AppWindow size={18}/></div><div className="license-identity"><strong>{String(item.customerName || item.ownerEmail)}</strong><small>{String(item.ownerEmail)} · •••••{String(item.keySuffix || "")}</small><div><i className={`state-pill ${item.status !== "active" ? "state-off" : ""}`}>{String(item.status)}</i><span>{String(item.plan).toUpperCase()}</span><span>{Number(item.maxDevices || 1)} cihaz</span></div></div><div className="license-products">{(item.products as string[] || []).map(product => <em key={product}>{products.find(x => x[0] === product)?.[1] || product}</em>)}</div><div className="license-actions">{item.status === "active" ? <button onClick={() => void updateStatus(item.id, "suspended")}><Ban size={15}/> Askıya al</button> : <button onClick={() => void updateStatus(item.id, "active")}><CheckCircle2 size={15}/> Etkinleştir</button>}<button className="danger" aria-label="Lisansı iptal et" onClick={() => void updateStatus(item.id, "revoked")}><Ban size={15}/></button></div></article>)}</section>
      <aside className="admin-panel license-feed"><PanelHead icon={Activity} title="Aktivasyon akışı" subtitle="Canlı güvenlik olayları"/>{events.slice(0, 14).map(event => <div key={event.id}><span/><p><strong>{String(event.type || "event").replaceAll("_", " ")}</strong><small>{String(event.productId || event.licenseId || "Sistem")}</small></p><time>{formatDate(event.createdAt)}</time></div>)}</aside></div>
    {showCreate && <div className="modal-backdrop" onClick={() => setShowCreate(false)}><form className="admin-modal license-create" onSubmit={createLicense} onClick={e => e.stopPropagation()}><p className="eyebrow">SECURE LICENSE ISSUER</p><h2>Yeni lisans oluştur</h2><div className="admin-form-grid"><label>Müşteri adı<input required value={form.customerName} onChange={e => setForm({...form, customerName:e.target.value})}/></label><label>E-posta<input required type="email" value={form.ownerEmail} onChange={e => setForm({...form, ownerEmail:e.target.value})}/></label><label>Plan<select value={form.plan} onChange={e => setForm({...form, plan:e.target.value})}><option value="trial">Trial</option><option value="pro">Pro</option><option value="business">Business</option><option value="lifetime">Lifetime</option></select></label><label>Uygulama<select value={form.product} onChange={e => setForm({...form, product:e.target.value})}>{products.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Cihaz limiti<input type="number" min="1" max="100" value={form.maxDevices} onChange={e => setForm({...form, maxDevices:e.target.value})}/></label><label>Offline grace<input type="number" min="1" max="30" value={form.offlineGraceDays} onChange={e => setForm({...form, offlineGraceDays:e.target.value})}/></label><label>Bitiş tarihi<input type="date" value={form.expiresAt} onChange={e => setForm({...form, expiresAt:e.target.value})}/></label><label>Not<textarea value={form.notes} onChange={e => setForm({...form, notes:e.target.value})}/></label></div><div className="license-modal-actions"><button type="button" onClick={() => setShowCreate(false)}>Vazgeç</button><button className="admin-action" type="submit"><KeyRound size={15}/> Güvenli lisans üret</button></div></form></div>}
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof KeyRound; label: string; value: number }) { return <div><span><Icon size={18}/></span><p><small>{label}</small><strong>{value}</strong></p></div>; }
function PanelHead({ icon: Icon, title, subtitle }: { icon: typeof KeyRound; title: string; subtitle: string }) { return <div className="panel-head"><div><span className="panel-icon"><Icon size={18}/></span><div><h2>{title}</h2><p>{subtitle}</p></div></div></div>; }
function formatDate(value: unknown) { const date = new Date(String(value || "")); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("tr-TR", { day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit" }).format(date) : "Şimdi"; }
